# Generated by Django 5.0 on 2023-12-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcode', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='Цифровой код')),
                ('charcode', models.CharField(max_length=3, verbose_name='Код валюта')),
                ('nominal', models.IntegerField(verbose_name='Номинальность')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.FloatField(verbose_name='Курс')),
                ('vunitrate', models.FloatField(verbose_name='Курс за единицу валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
