# Generated by Django 4.0 on 2023-12-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_cart_currencyincart_cart_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.ManyToManyField(related_name='carts', through='currency.CurrencyInCart', to='currency.Currency', verbose_name='Валюта'),
        ),
    ]
