# Generated by Django 5.0 on 2023-12-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_user_сurrencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='сurrencies',
            new_name='currencies',
        ),
    ]
