# Generated by Django 5.0 on 2023-12-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_rename_сurrencies_user_currencies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercurrency',
            options={'verbose_name': 'Пользователь-валюта', 'verbose_name_plural': 'Пользователи-валюты'},
        ),
    ]
