# Generated by Django 4.0 on 2023-12-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_email'),
        ('currency', '0003_alter_cart_currency'),
        ('customuser', '0005_alter_usercurrency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currencies',
            field=models.ManyToManyField(related_name='users', through='customuser.UserCurrency', to='currency.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
